version: "3"
services:
  db:
    image: "postgres:13.4"
    container_name: "my_postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "cleaning"
    ports:
      - "5432:5432"
    volumes:
      - ./my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata: